services:
  qdrant:
    container_name: qdrant_service
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
  embed:
    container_name: embed_service
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.5
    ports:
      - "8080:80"
    volumes:
      - ./data:/data
    command: ["--model-id", "BAAI/bge-m3", "--revision", "refs/pr/5", "--port", "8080", "--platform", "linux/arm64"]

